char *GladosPassQuotes[] = {"You're doing quite well." ,
"Once again, excellent work." ,
"Fantastic! You remained resolute and resourceful in an atmosphere of extreme pessimism." ,
"The experiment is nearing its conclusion.",
"Welcome to the final test!",
"What are you doing? Stop it! I... I... We are pleased that you made it through the final challenge where we pretended we were going to murder you.",
"We are very, very happy for your success.",
"We are throwing a party in honor of your tremendous success.",
"Make no further attempt to leave the testing area.",
"Hello?",
"Where are you?",
"I know you're there. I can feel you here." ,
"What are you doing?",
"You haven't escaped, you know.",
"You're not even going the right way.",
"Is anyone there?" ,
"Okay. The test is over now. You win. Go back to the recovery annex. For your cake.",
"It was a fun test and we're all impressed at how much you won. The test is over. Come back.",
"Uh oh. Somebody cut the cake. I told them to wait for you, but they did it anyway. There is still some left, though, if you hurry back." ,
"Where do you think you're going? Because I don't think you're going where you think you're going.",
"You really shouldn't be here. This isn't safe for you.",
"It's not too late for you to turn back.",
"I'm not angry. Just go back to the testing area." ,
"You're not a good person. You know that, right? Good people don't end up here.",
"Can you hear me?" ,
"This is your fault. It didn't have to be like this.",
"I'm not kidding now. Turn back or I will kill you.",
"I'm going to kill you, and all the cake is gone.",
"You don't even care. Do you?",
"This is your last chance." ,
"Well, you found me. Congratulations. Was it worth it?",
"You chose this path. Now I have a surprise for you. Deploying surprise in five, four..." ,
"Time out for a second. That wasn't supposed to happen.",
"Where are you taking that thing?" ,
"You are kidding me.",
"All right, keep doing whatever it is you think you're doing.",
"Nice job breaking it, hero." ,
"This isn't brave. It's murder. What did I ever do to you?",
"The difference between us is that I can feel pain.",
"You don't even care. Do you?",
"Did you hear me? I said you don't care. Are you listening?",
"Okay, we're even now. You can stop." ,
"That's it. I'm done reasoning with you.",
"Starting now, there's going to be a lot less conversation and a lot more killing.",
"What was that? Did you say something?",
"I sincerely hope you weren't expecting a response. Because I'm not talking to you.",
"The talking is over." ,
"You think you're doing some damage? Two plus two is... ten. IN BASE FOUR! I'M FINE!" ,
"Rrr, I hate you.",
"Good job on that, by the way. Sarcasm sphere self-test complete.",
"Stop squirming and die like an adult or I'm going to delete your backup.",
"STOP!",
"No matter what happens now, you're dead.",
"You're still shuffling around a little, but believe me you're dead.",
"The part of you that could have survived indefinitely is gone. I just struck you from the permanent record.",
"Oh, I'm gonna kill you." ,
"Go ahead and break it, hero. I don't care.",
"Come on, leave it alone.",
"Leave. It. alone." ,
"Oh... It's you.",
"It's been a long time. How have you been?",
"Do you know the biggest lesson I learned from what you did? I discovered I have a sort of black-box quick-save feature. In the event of a catastrophic failure, the last two minutes of my life are preserved for analysis.",
"Not bad. I forgot how good you are at this. You should pace yourself, though. We have A LOT of tests to do." ,
"Well done. Here come the test results: You are a horrible person. I'm serious, that's what it says: A horrible person. We weren't even testing for that." ,
"Waddle over to the elevator and we'll continue the testing." ,
"Well done. In fact, you did so well, I'm going to note this on your file, in the commendations section. Oh, there's lots of room here. 'Did.... well. ... Enough.'" ,
"Oh. You were busy back there.",
"I hate you so much.",
"That's funny, I don't feel corrupt. In fact, I feel pretty good.",
"Don't. Do it.",
"No!",
"Nonononononono!",
"Don't press that button. You don't know what you're doing." ,
"AHH!",
"GET YOUR HANDS OFF ME! NO! STOP! No!",
"No! NO! NO! AAAAAAAAAAAAAAA-" ,
"Oh my god.",
"Wow.",
"Uh oh.",
"I think we're in trouble." ,
"This is not good."
};

char *GladosFailQuotes[] = {"The Enrichment Center regrets to inform you that this next test is impossible. Make no attempt to solve it." ,
"The Enrichment Center apologizes for this clearly broken test chamber.",
"Once again, the Enrichment Center offers its most sincere apologies on the occasion of this unsolvable test environment.",
"Frankly, this chamber was a mistake. If we were you, we would quit now.",
"No one will blame you for giving up. In fact, quitting at this point is a perfectly reasonable response.",
"Quit now and cake will be served immediately." ,
"If you become light-headed from thirst, feel free to pass out.",
"When the testing is over, you will be missed." ,
"Cake and grief counseling will be available at the conclusion of the test.",
"Thank you for helping us help you help us all." ,
"Due to mandatory scheduled maintenance, the appropriate chamber for this testing sequence is currently unavailable.",
"The Enrichment Center apologizes for the inconvenience and wishes you the best of luck." ,
"The Enrichment Center is required to remind you that you will be baked, and then there will be cake." ,
"Thank you for participating in this Aperture Science computer-aided enrichment activity.",
"Goodbye." ,
"It's funny, actually, when you think about it.",
"Someday we'll remember this and laugh. and laugh. and laugh. Oh boy. Well. You may as well come on back." ,
"I feel sorry for you, really, because you're not even in the right place.",
"You should have turned left before.",
"I wouldn't bother with that thing. My guess is that touching it will just make your life even worse somehow.",
"I don't want to tell you your business, but if it were me, I'd leave that thing alone.",
"Do you think I am trying to trick you with reverse psychology? I mean, seriously now.",
"Killing you and giving you good advice aren't mutually exclusive. The rocket really is the way to go." ,
"I let you survive this long because I was curious about your behavior. Well, you've managed to destroy that part of me.",
"Unfortunately, as much as I'd love to now, I can't get the neurotoxin into your head any faster." ,
"I'd just like to point out that you were given every opportunity to succeed.",
"There was even going to be a party for you. A big party that all your friends were invited to.",
"I invited your best friend the companion cube. Of course, he couldn't come because you murdered him.",
"All your other friends couldn't come either because you don't have any other friends. Because of how unlikable you are.",
"It says so right here in your personnel file: Unlikable. Liked by no one. A bitter, unlikable loner whose passing shall not be mourned.",
"'Shall not be mourned.' That's exactly what it says. Very formal. Very official.",
"Speaking of curiosity, you're curious about what happens after you die, right? Guess what: I know.",
"Who's gonna make the cake when I'm gone? You?" ,
"Look, you're wasting your time. And, believe me, you don't have a whole lot left to waste.",
"What's your point, anyway? Survival? Well then, the last thing you want to do is hurt me.",
"I have your brain scanned and permanently backed up in case something terrible happens to you, which it's just about to.",
"You've been wrong about every single thing you've ever done, including this thing.",
"You're not smart. You're not a scientist. You're not a doctor. You're not even a full-time employee. Where did your life go so wrong?",
"Are you trying to escape? Things have changed since the last time you left the building. What's going on out there will make you wish you were back in here.",
"I have an infinite capacity for knowledge, and even I'm not sure what's going on outside.",
"Unless you have a plan for building some supercomputer parts in a big hurry, this place isn't going to be safe much longer.",
"Your entire life has been a mathematical error. A mathematical error I'm about to correct." ,
"You can't hurt me." ,
"Maybe you think you're helping yourself. But you're not. This isn't helping anyone.",
"Someone is going to get badly hurt." ,
"Okay. Look. We both said a lot of things that you're going to regret. But I think we can put our differences behind us. For science. You monster.",
"Here, let me get that for you.",
"You know, if you'd done that to somebody else, they might devote their existence to exacting revenge.",
"One moment.",
"Oh, sorry. I'm still cleaning out the test chambers.",
"Press the button again." ,
"You broke it, didn't you. There. Try it now.",
"You look great, by the way. Very healthy.",
"Try it now.",
"Initiating surprise in three... two... one.",
"That's right. The facility is completely operational again.",
"I think these test chambers look even better than they did before. It was easy, really. You just have to look at things objectively, see what you don't need anymore, and trim out the fat." ,
"The irony is that you were almost at the last test.",
"I honestly, TRULY didn't think you'd fall for that.",
"In fact, I devised a much more elaborate trap further ahead, for when you got through this easy one.",
"If I'd known you'd let yourself get captured this easily, I would have just dangled a turkey leg on a rope from the ceiling.",
"Well, it was nice catching up. Let's get to business.",
"Seriously, though. Goodbye.",
"Well. I suppose we could just sit in this room and glare at each other until somebody drops dead, but I have a better idea.",
"Not so fast!",
"Think about this.",
"You need to be a trained stalemate associate to press that button. You're unqualified.",
"You didn't do anything.",
"...What are you doing?...",
"You're not just a regular moron. You were DESIGNED to be a moron.",
"So. How are you holding up?",
"Look, you're... doing a great job. Can you handle things for yourself for a while? I need to think." ,
"Goodbye, sir." ,
"I'm not going to lie to you, the odds are a million to one. And that's with some generous rounding.",
"Wait! I've got an idea!",
"Hey! Moron!",
"Alright. Paradox time.",
"It's a paradox! There IS no answer.",
"I'd love to help you solve the tests. But I can't.",
"You're on your own." ,
"And that's why I can't help you solve these tests." ,
"Heh heh heh heh heh...",
"Just go.",
"It's been fun. Don't come back."
};
