AUTHOR_ID  = VITOG
SERVICE_ID = 00001
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed $(GENFLAGS)
VULN_COUNT = 1
POLLS_RELEASE_COUNT = 5

NO_CB_EXTENDED_APP = 1
NO_CB_DPKG = 1

include cgc-cb.mk
